# Workflow - Publish to GitHub Packages
name: deploy-workflow

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  execute:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job-self.yml@main
    secrets: inherit
    with:
      repo: ${{ github.repository }}
      with_image: true


