# Workflow - build, publish jar and image to GitHub Packages for this repository(msa-rms-service-item)
name: deploy-workflow

on:
  workflow_dispatch:

jobs:
  execute:
    uses: extact-io/msa-rms-parent/.github/workflows/deploy-job.yml@main
    with:
      repo: ${{ github.repository }}
      with_image: true
      deploy_type: ecs
      ecs_taskname: item-service-task
      ecs_containername: item-service-container
      ecs_servicename: item-service
    secrets: inherit
